title: Adrian Moreno
# sub_title: Passionate front-end developer.&ensp;Software engineer
sub_title: Passionate front-end development
meta_title: Adrian Moreno | Homepage
description: Software development and coding stuff
baseurl: ""             # the subpath of your site, e.g. /blog
url: "http://adriem.me" # the base hostname & protocol for your site
copyright: '&copy; 2016-2017 Adri√°n Moreno'

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      language: en

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-coffeescript
  - jekyll-redirect-from
